"""more db fixes

Revision ID: 5dfe8b0dfb91
Revises: f38995b1d8c5
Create Date: 2026-07-18 23:04:24.364720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dfe8b0dfb91'
down_revision: Union[str, None] = 'f38995b1d8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status'),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status', schema='auctora_dev'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status'),
               type_=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status', schema='auctora_dev'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema='auctora_dev') as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles'),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               existing_nullable=False)

    with op.batch_alter_table('wallet_transactions', schema='auctora_dev') as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types'),
               type_=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types', schema='auctora_dev'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status', schema='auctora_dev'),
               existing_nullable=False)
        batch_op.drop_constraint('uq_wallet_transactions_reference_id', type_='unique')
        batch_op.drop_index('ix_auctora_dev_wallet_transactions_reference_id')
        batch_op.create_index(batch_op.f('ix_auctora_dev_wallet_transactions_reference_id'), ['reference_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema='auctora_dev') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auctora_dev_wallet_transactions_reference_id'))
        batch_op.create_index('ix_auctora_dev_wallet_transactions_reference_id', ['reference_id'], unique=False)
        batch_op.create_unique_constraint('uq_wallet_transactions_reference_id', ['reference_id'])
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status', schema='auctora_dev'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status'),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types', schema='auctora_dev'),
               type_=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema='auctora_dev') as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status', schema='auctora_dev'),
               type_=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status'),
               existing_nullable=False)

    with op.batch_alter_table('auctions', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status', schema='auctora_dev'),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status'),
               existing_nullable=False)

    # ### end Alembic commands ###
