"""resync outdated db

Revision ID: 838b8a269c59
Revises: 
Create Date: 2026-01-26 20:39:22.940645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '838b8a269c59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status'),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status', schema='auctora_dev'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status'),
               type_=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status', schema='auctora_dev'),
               existing_nullable=False)

    with op.batch_alter_table('reward_history', schema='auctora_dev') as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_auctora_dev_reward_history_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('reward_history_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')
        batch_op.drop_column('description')

    with op.batch_alter_table('users', schema='auctora_dev') as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles'),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               existing_nullable=False)
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referral_slots_used')
        batch_op.drop_column('referred_users')
        batch_op.drop_column('referral_commisions_paid')
        batch_op.drop_column('referral_debt_settled')

    with op.batch_alter_table('wallet_transactions', schema='auctora_dev') as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types'),
               type_=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types', schema='auctora_dev'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status', schema='auctora_dev'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status', schema='auctora_dev'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status'),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types', schema='auctora_dev'),
               type_=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema='auctora_dev') as batch_op:
        batch_op.add_column(sa.Column('referral_debt_settled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referral_commisions_paid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referred_users', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referral_slots_used', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles'),
               existing_nullable=False)

    with op.batch_alter_table('reward_history', schema='auctora_dev') as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reward_history_user_id_fkey', 'users', ['user_id'], ['id'], referent_schema='auctora_dev')
        batch_op.drop_index(batch_op.f('ix_auctora_dev_reward_history_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('type')

    with op.batch_alter_table('payments', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status', schema='auctora_dev'),
               type_=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status'),
               existing_nullable=False)

    with op.batch_alter_table('auctions', schema='auctora_dev') as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status', schema='auctora_dev'),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status'),
               existing_nullable=False)

    # ### end Alembic commands ###
