"""Updated item-auction relationship

Revision ID: 02b19375fecb
Revises: af193f20f681
Create Date: 2025-01-24 12:06:39.424397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b19375fecb'
down_revision: Union[str, None] = 'af193f20f681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auctora_dev_auctions_item_id', table_name='auctions', schema='auctora_dev')
    op.drop_constraint('auctions_item_id_fkey', 'auctions', schema='auctora_dev', type_='foreignkey')
    op.drop_column('auctions', 'item_id', schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=True), schema='auctora_dev')
    op.create_foreign_key('auctions_item_id_fkey', 'auctions', 'items', ['item_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev')
    op.create_index('ix_auctora_dev_auctions_item_id', 'auctions', ['item_id'], unique=False, schema='auctora_dev')
    # ### end Alembic commands ###
