"""updated auction table

Revision ID: 033996d743d4
Revises: 6152d6d61208
Create Date: 2025-01-15 22:05:36.269653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033996d743d4'
down_revision: Union[str, None] = '6152d6d61208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('start_price', sa.Float(), nullable=False), schema='auctora_dev')
    op.add_column('auctions', sa.Column('current_price', sa.Float(), nullable=False), schema='auctora_dev')
    op.add_column('auctions', sa.Column('buy_now', sa.Boolean(), nullable=False), schema='auctora_dev')
    op.add_column('auctions', sa.Column('buy_now_price', sa.Float(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'buy_now_price', schema='auctora_dev')
    op.drop_column('auctions', 'buy_now', schema='auctora_dev')
    op.drop_column('auctions', 'current_price', schema='auctora_dev')
    op.drop_column('auctions', 'start_price', schema='auctora_dev')
    # ### end Alembic commands ###
