"""added google_id to user.model

Revision ID: 084626a1f7b8
Revises: fd27cb97b290
Create Date: 2025-05-10 21:32:44.762009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084626a1f7b8'
down_revision: Union[str, None] = 'fd27cb97b290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_id', schema='auctora_dev')
    # ### end Alembic commands ###
