"""auction-logistics

Revision ID: 08cad63dbf7b
Revises: 3c864aaf9eab
Create Date: 2025-05-08 01:34:54.627469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cad63dbf7b'
down_revision: Union[str, None] = '3c864aaf9eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE auctora_dev.auctions
        ALTER COLUMN logistic_type TYPE JSON
        USING logistic_type::json
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'logistic_type',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               schema='auctora_dev')
    # ### end Alembic commands ###
