"""Updated item-auction relationship

Revision ID: 1a486882874c
Revises: 02b19375fecb
Create Date: 2025-01-24 12:43:49.182018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a486882874c'
down_revision: Union[str, None] = '02b19375fecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('auction_id', sa.UUID(), nullable=True), schema='auctora_dev')
    op.create_foreign_key(None, 'items', 'auctions', ['auction_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', schema='auctora_dev', type_='foreignkey')
    op.drop_column('items', 'auction_id', schema='auctora_dev')
    # ### end Alembic commands ###
