"""added auctions.refundable

Revision ID: 1afae5484275
Revises: 440ba095984f
Create Date: 2025-05-14 17:28:51.019776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1afae5484275'
down_revision: Union[str, None] = '440ba095984f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('refundable', sa.Boolean(), nullable=True), schema='auctora_dev')
    op.alter_column('payments', 'due_data',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'due_data',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='auctora_dev')
    op.drop_column('auctions', 'refundable', schema='auctora_dev')
    # ### end Alembic commands ###
