"""updated user model

Revision ID: 210f8410a136
Revises: ba8b3227ccde
Create Date: 2025-03-04 13:47:44.242629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210f8410a136'
down_revision: Union[str, None] = 'ba8b3227ccde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank_name', sa.String(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_name', schema='auctora_dev')
    # ### end Alembic commands ###
