"""Update item model

Revision ID: 3d4a95246d2f
Revises: d99bed8474d4
Create Date: 2025-01-06 21:16:01.291274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d4a95246d2f'
down_revision: Union[str, None] = 'd99bed8474d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'image_link',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'image_link',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='auctora_dev')
    # ### end Alembic commands ###
