"""Updated item-auction relationship

Revision ID: 42eb002e2792
Revises: 20450cb0ba71
Create Date: 2025-01-24 13:07:08.988285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42eb002e2792'
down_revision: Union[str, None] = '20450cb0ba71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_auction_id_fkey', 'items', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'auctions', ['auction_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key('items_auction_id_fkey', 'items', 'auctions', ['auction_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev')
    # ### end Alembic commands ###
