"""adjust payments.due_date to be nullable

Revision ID: 440ba095984f
Revises: 4aad3ff7d48c
Create Date: 2025-05-13 16:10:01.192934

"""
from typing import Sequence, Union
from datetime import datetime, timedelta

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440ba095984f'
down_revision: Union[str, None] = '4aad3ff7d48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'payments',
        'due_data',
        existing_type=sa.String(),
        existing_nullable=True,
        server_default=None,
        nullable=False,
        schema='auctora_dev'
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'payments',
        'due_data',
        existing_type=sa.String(),
        existing_nullable=False,
        existing_server_default=None,
        server_default=sa.text(datetime.now().astimezone() + timedelta(days=3)),
        nullable=True,
        schema='auctora_dev'
    )
    pass
    # ### end Alembic commands ###
