"""update user model for referrals

Revision ID: 44704c3fa208
Revises: 7e31c996d0a9
Create Date: 2025-04-24 01:26:08.351148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44704c3fa208'
down_revision: Union[str, None] = '7e31c996d0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by', sa.String(), nullable=True), schema='auctora_dev')
    op.add_column('users', sa.Column('referral_debt_settled', sa.Boolean(), nullable=True), schema='auctora_dev')
    op.add_column('users', sa.Column('referral_code', sa.String(), nullable=True), schema='auctora_dev')
    op.add_column('users', sa.Column('referred_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referred_users', schema='auctora_dev')
    op.drop_column('users', 'referral_code', schema='auctora_dev')
    op.drop_column('users', 'referral_debt_settled', schema='auctora_dev')
    op.drop_column('users', 'referred_by', schema='auctora_dev')
    # ### end Alembic commands ###
