"""baseline

Revision ID: 57f1fbfa564b
Revises: 
Create Date: 2025-10-24 12:08:14.211759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57f1fbfa564b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('main_image', sa.String(length=255), nullable=True),
    sa.Column('estimated_reading_time', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auctora_dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auctora_dev'
    )
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auctora_dev_blogs_id'), ['id'], unique=False)

    op.create_table('blog_comments',
    sa.Column('blog_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['auctora_dev.blogs.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['auctora_dev.blog_comments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auctora_dev'
    )
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auctora_dev_blog_comments_id'), ['id'], unique=False)

    op.drop_table('alembic_version')
    with op.batch_alter_table('Bids', schema=None) as batch_op:
        batch_op.drop_constraint('Bids_auction_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Bids_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'auctions', ['auction_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')

    with op.batch_alter_table('auction_participants', schema=None) as batch_op:
        batch_op.drop_constraint('auction_participants_auction_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'auctions', ['auction_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')

    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status'),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status', schema='auctora_dev'),
               existing_nullable=False)
        batch_op.drop_constraint('auctions_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('items_auction_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('items_users_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('items_sub_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'auctions', ['auction_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'subcategories', ['sub_category_id'], ['id'], referent_schema='auctora_dev')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], referent_schema='auctora_dev')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status'),
               type_=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status', schema='auctora_dev'),
               existing_nullable=False)
        batch_op.drop_constraint('payments_to_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('payments_auction_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('payments_from_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['to_id'], ['id'], referent_schema='auctora_dev', ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'auctions', ['auction_id'], ['id'], referent_schema='auctora_dev', ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['from_id'], ['id'], referent_schema='auctora_dev', ondelete='SET NULL')

    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_constraint('subcategories_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'], referent_schema='auctora_dev')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles'),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               existing_nullable=False)

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types'),
               type_=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types', schema='auctora_dev'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status', schema='auctora_dev'),
               existing_nullable=False)
        batch_op.drop_constraint('wallet_transactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='auctora_dev', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wallet_transactions_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status', schema='auctora_dev'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transaction_status'),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types', schema='auctora_dev'),
               type_=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles'),
               existing_nullable=False)

    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subcategories_parent_id_fkey', 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_from_id_fkey', 'users', ['from_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('payments_auction_id_fkey', 'auctions', ['auction_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('payments_to_id_fkey', 'users', ['to_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status', schema='auctora_dev'),
               type_=postgresql.ENUM('INSPECTING', 'PENDING', 'COMPLETED', 'REFUNDED', 'REFUNDING', name='payment_status'),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('items_sub_category_id_fkey', 'subcategories', ['sub_category_id'], ['id'])
        batch_op.create_foreign_key('items_users_id_fkey', 'users', ['users_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('items_auction_id_fkey', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('items_category_id_fkey', 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('auctions_users_id_fkey', 'users', ['users_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status', schema='auctora_dev'),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCLED', 'PENDING', name='auction_status'),
               existing_nullable=False)

    with op.batch_alter_table('auction_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('auction_participants_auction_id_fkey', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Bids', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Bids_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('Bids_auction_id_fkey', 'auctions', ['auction_id'], ['id'], ondelete='CASCADE')

    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auctora_dev_blog_comments_id'))

    op.drop_table('blog_comments', schema='auctora_dev')
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auctora_dev_blogs_id'))

    op.drop_table('blogs', schema='auctora_dev')
    # ### end Alembic commands ###
