"""Reduced user models init

Revision ID: 582b687a4f7a
Revises: c14c20ec1d2e
Create Date: 2025-02-14 13:59:13.401090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582b687a4f7a'
down_revision: Union[str, None] = 'c14c20ec1d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='auctora_dev')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='auctora_dev')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='auctora_dev')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='auctora_dev')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='auctora_dev')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='auctora_dev')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='auctora_dev')
    # ### end Alembic commands ###
