"""updated items.users_id foreign constraint ondelete rule

Revision ID: 5b31acbe24d7
Revises: c14a72d4a085
Create Date: 2025-04-08 15:33:22.459661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b31acbe24d7'
down_revision: Union[str, None] = 'c14a72d4a085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_users_id_fkey', 'items', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['users_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev', ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key('items_users_id_fkey', 'items', 'users', ['users_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev')
    # ### end Alembic commands ###
