"""revised relationship variables

Revision ID: 6152d6d61208
Revises: f8411a1b59b2
Create Date: 2025-01-15 21:19:16.825365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6152d6d61208'
down_revision: Union[str, None] = 'f8411a1b59b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'current_price', schema='auctora_dev')
    op.drop_column('items', 'quantity', schema='auctora_dev')
    op.drop_column('items', 'starting_price', schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('starting_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='auctora_dev')
    op.add_column('items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False), schema='auctora_dev')
    op.add_column('items', sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='auctora_dev')
    # ### end Alembic commands ###
