"""changed watchers model

Revision ID: 65f6c00b36f1
Revises: 210f8410a136
Create Date: 2025-03-20 13:28:59.432161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f6c00b36f1'
down_revision: Union[str, None] = '210f8410a136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('auctions', 'watchers',
#                existing_type=sa.INTEGER(),
#                type_=sa.JSON(),
#                existing_nullable=True,
#                schema='auctora_dev')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('auctions', 'watchers',
#                existing_type=sa.JSON(),
#                type_=sa.INTEGER(),
#                existing_nullable=True,
#                schema='auctora_dev')
#     # ### end Alembic commands ###

def upgrade() -> None:
    # Manually alter the column using raw SQL with the USING clause
    op.execute("""
        ALTER TABLE auctora_dev.auctions 
        ALTER COLUMN watchers TYPE JSON 
        USING to_json(watchers);
    """)

def downgrade() -> None:
    # Convert JSON back to INTEGER (assuming JSON values are always integers)
    op.execute("""
        ALTER TABLE auctora_dev.auctions 
        ALTER COLUMN watchers TYPE INTEGER 
        USING (watchers::integer);
    """)
