"""Migration

Revision ID: 675f956345b8
Revises: 6e35d6ae674b
Create Date: 2025-02-14 15:51:00.301917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675f956345b8'
down_revision: Union[str, None] = '6e35d6ae674b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_verified', sa.Boolean(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_verified', schema='auctora_dev')
    # ### end Alembic commands ###
