"""first migration

Revision ID: 7f3d8e502557
Revises: 
Create Date: 2025-01-01 23:33:53.136125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3d8e502557'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auctora_dev'
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auctora_dev'
    )
    op.create_index(op.f('ix_auctora_dev_users_email'), 'users', ['email'], unique=True, schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_users_id'), 'users', ['id'], unique=False, schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_users_username'), 'users', ['username'], unique=True, schema='auctora_dev')
    op.create_table('subcategories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['auctora_dev.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auctora_dev'
    )
    op.create_index(op.f('ix_auctora_dev_subcategories_name'), 'subcategories', ['name'], unique=False, schema='auctora_dev')
    op.create_table('items',
    sa.Column('sellers_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('starting_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('image_link', sa.JSON(), nullable=False),
    sa.Column('image_link_2', sa.JSON(), nullable=True),
    sa.Column('image_link_3', sa.JSON(), nullable=True),
    sa.Column('image_link_4', sa.JSON(), nullable=True),
    sa.Column('image_link_5', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('sub_category_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['auctora_dev.categories.id'], ),
    sa.ForeignKeyConstraint(['sellers_id'], ['auctora_dev.users.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['auctora_dev.subcategories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auctora_dev'
    )
    op.create_index(op.f('ix_auctora_dev_items_id'), 'items', ['id'], unique=False, schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctora_dev_items_id'), table_name='items', schema='auctora_dev')
    op.drop_table('items', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_subcategories_name'), table_name='subcategories', schema='auctora_dev')
    op.drop_table('subcategories', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_users_username'), table_name='users', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_users_id'), table_name='users', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_users_email'), table_name='users', schema='auctora_dev')
    op.drop_table('users', schema='auctora_dev')
    op.drop_table('categories', schema='auctora_dev')
    # ### end Alembic commands ###
