"""items.users_id ondelete to cascade

Revision ID: 81afa6826dab
Revises: 084626a1f7b8
Create Date: 2025-05-13 01:01:33.826004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81afa6826dab'
down_revision: Union[str, None] = '084626a1f7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_users_id_fkey', 'items', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['users_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key('items_users_id_fkey', 'items', 'users', ['users_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev', ondelete='SET DEFAULT')
    # ### end Alembic commands ###
