"""restructured notif model

Revision ID: 81fc26b1465b
Revises: acd7d098f5c1
Create Date: 2025-06-03 16:49:36.495151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fc26b1465b'
down_revision: Union[str, None] = 'acd7d098f5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('links', sa.JSON(), nullable=True), schema='auctora_dev')
    op.add_column('notifications', sa.Column('class_name', sa.String(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'class_name', schema='auctora_dev')
    op.drop_column('notifications', 'links', schema='auctora_dev')
    # ### end Alembic commands ###
