"""auction.reserve_price

Revision ID: 90d40c6e3f43
Revises: 81fc26b1465b
Create Date: 2025-07-03 12:01:09.248407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d40c6e3f43'
down_revision: Union[str, None] = '81fc26b1465b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('reserve_price', sa.Float(), nullable=True, default=0.0), schema='auctora_dev')
    op.add_column('auctions', sa.Column('use_reserve_price', sa.Boolean(), nullable=True, default=False), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'use_reserve_price', schema='auctora_dev')
    op.drop_column('auctions', 'reserve_price', schema='auctora_dev')
    # ### end Alembic commands ###
