"""update wallet enums

Revision ID: 94323c3e7ac4
Revises: d97429210012
Create Date: 2025-02-03 13:58:31.962729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94323c3e7ac4'
down_revision: Union[str, None] = 'd97429210012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'transaction_type',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               type_=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types', schema='auctora_dev'),
               existing_nullable=False,
               schema='auctora_dev')
    op.alter_column('wallet_transactions', 'status',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='transaction_status', schema='auctora_dev'),
               existing_nullable=False,
               schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='transaction_status', schema='auctora_dev'),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               existing_nullable=False,
               schema='auctora_dev')
    op.alter_column('wallet_transactions', 'transaction_type',
               existing_type=postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='transaction_types', schema='auctora_dev'),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', name='userroles', schema='auctora_dev'),
               existing_nullable=False,
               schema='auctora_dev')
    # ### end Alembic commands ###
