"""remove nullable constraint in Bids_username

Revision ID: 992f97dc796c
Revises: 675f956345b8
Create Date: 2025-02-19 16:33:33.873914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992f97dc796c'
down_revision: Union[str, None] = '675f956345b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bids', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bids', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='auctora_dev')
    # ### end Alembic commands ###
