"""Updated constraint on FK relationships

Revision ID: 9d19f445bbf9
Revises: 42eb002e2792
Create Date: 2025-01-24 13:12:53.273509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d19f445bbf9'
down_revision: Union[str, None] = '42eb002e2792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auction_participants_auction_id_fkey', 'auction_participants', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key(None, 'auction_participants', 'auctions', ['auction_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev', ondelete='CASCADE')
    op.drop_constraint('auctions_users_id_fkey', 'auctions', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key(None, 'auctions', 'users', ['users_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auctions', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key('auctions_users_id_fkey', 'auctions', 'users', ['users_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev')
    op.drop_constraint(None, 'auction_participants', schema='auctora_dev', type_='foreignkey')
    op.create_foreign_key('auction_participants_auction_id_fkey', 'auction_participants', 'auctions', ['auction_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev')
    # ### end Alembic commands ###
