"""added rating_count to users

Revision ID: aa4d4a55edbb
Revises: 81afa6826dab
Create Date: 2025-05-13 01:38:45.927061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4d4a55edbb'
down_revision: Union[str, None] = '81afa6826dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating_count', sa.Integer(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating_count', schema='auctora_dev')
    # ### end Alembic commands ###
