"""added attr for refunds

Revision ID: acd7d098f5c1
Revises: 1afae5484275
Create Date: 2025-06-03 15:45:14.010826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd7d098f5c1'
down_revision: Union[str, None] = '1afae5484275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE auctora_dev.payment_status ADD VALUE IF NOT EXISTS 'REFUNDING'")
    op.add_column('payments', sa.Column('refund_requested', sa.Boolean(), nullable=True), schema='auctora_dev')
    op.add_column('payments', sa.Column('seller_refund_confirmed', sa.Boolean(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'seller_refund_confirmed', schema='auctora_dev')
    op.drop_column('payments', 'refund_requested', schema='auctora_dev')
    # ### end Alembic commands ###
