"""removed unique contraint on Bid.username

Revision ID: c14a72d4a085
Revises: d4fccce0ab73
Create Date: 2025-04-02 21:16:31.578241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14a72d4a085'
down_revision: Union[str, None] = 'd4fccce0ab73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Bids_username_key', 'Bids', schema='auctora_dev', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Bids_username_key', 'Bids', ['username'], schema='auctora_dev')
    # ### end Alembic commands ###
