"""Added reference id to transaction model

Revision ID: c14c20ec1d2e
Revises: 94323c3e7ac4
Create Date: 2025-02-13 13:24:25.671649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14c20ec1d2e'
down_revision: Union[str, None] = '94323c3e7ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('reference_id', sa.String(), nullable=True), schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_wallet_transactions_reference_id'), 'wallet_transactions', ['reference_id'], unique=False, schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctora_dev_wallet_transactions_reference_id'), table_name='wallet_transactions', schema='auctora_dev')
    op.drop_column('wallet_transactions', 'reference_id', schema='auctora_dev')
    # ### end Alembic commands ###
