"""added watchers count

Revision ID: d4fccce0ab73
Revises: 65f6c00b36f1
Create Date: 2025-03-20 14:26:57.169438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fccce0ab73'
down_revision: Union[str, None] = '65f6c00b36f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('watchers_count', sa.Integer(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'watchers_count', schema='auctora_dev')
    # ### end Alembic commands ###
