"""added wallet transaction and bid tables

Revision ID: d97429210012
Revises: 9d19f445bbf9
Create Date: 2025-01-27 15:23:38.101683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd97429210012'
down_revision: Union[str, None] = '9d19f445bbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bids', sa.Column('username', sa.String(), nullable=False), schema='auctora_dev')
    op.create_unique_constraint(None, 'Bids', ['username'], schema='auctora_dev')
    op.create_index('ix_auctions_status_end_date', 'auctions', ['status', 'end_date'], unique=False, schema='auctora_dev')
    op.create_index('ix_auctions_status_start_date', 'auctions', ['status', 'start_date'], unique=False, schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_auctions_end_date'), 'auctions', ['end_date'], unique=False, schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_auctions_start_date'), 'auctions', ['start_date'], unique=False, schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_auctions_status'), 'auctions', ['status'], unique=False, schema='auctora_dev')
    op.add_column('users', sa.Column('wallet', sa.Float(), nullable=True), schema='auctora_dev')
    op.add_column('users', sa.Column('available_balance', sa.Float(), nullable=True), schema='auctora_dev')
    op.add_column('users', sa.Column('auctioned_amount', sa.Float(), nullable=True), schema='auctora_dev')
    op.add_column('wallet_transactions', sa.Column('user_id', sa.UUID(), nullable=True), schema='auctora_dev')
    op.add_column('wallet_transactions', sa.Column('amount', sa.Float(), nullable=False), schema='auctora_dev')
    op.add_column('wallet_transactions', sa.Column('description', sa.String(), nullable=True), schema='auctora_dev')
    op.add_column('wallet_transactions', sa.Column('transaction_type', postgresql.ENUM('FUNDING', 'WITHDRAWAL', 'CREDIT', 'DEBIT', name='userroles', schema='auctora_dev'), nullable=False), schema='auctora_dev')
    op.add_column('wallet_transactions', sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='userroles', schema='auctora_dev'), nullable=False), schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False, schema='auctora_dev')
    op.create_foreign_key(None, 'wallet_transactions', 'users', ['user_id'], ['id'], source_schema='auctora_dev', referent_schema='auctora_dev', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', schema='auctora_dev', type_='foreignkey')
    op.drop_index(op.f('ix_auctora_dev_wallet_transactions_user_id'), table_name='wallet_transactions', schema='auctora_dev')
    op.drop_column('wallet_transactions', 'status', schema='auctora_dev')
    op.drop_column('wallet_transactions', 'transaction_type', schema='auctora_dev')
    op.drop_column('wallet_transactions', 'description', schema='auctora_dev')
    op.drop_column('wallet_transactions', 'amount', schema='auctora_dev')
    op.drop_column('wallet_transactions', 'user_id', schema='auctora_dev')
    op.drop_column('users', 'auctioned_amount', schema='auctora_dev')
    op.drop_column('users', 'available_balance', schema='auctora_dev')
    op.drop_column('users', 'wallet', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_auctions_status'), table_name='auctions', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_auctions_start_date'), table_name='auctions', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_auctions_end_date'), table_name='auctions', schema='auctora_dev')
    op.drop_index('ix_auctions_status_start_date', table_name='auctions', schema='auctora_dev')
    op.drop_index('ix_auctions_status_end_date', table_name='auctions', schema='auctora_dev')
    op.drop_constraint(None, 'Bids', schema='auctora_dev', type_='unique')
    op.drop_column('Bids', 'username', schema='auctora_dev')
    # ### end Alembic commands ###
