"""Update item model

Revision ID: d99bed8474d4
Revises: 66a2f05c1d92
Create Date: 2025-01-06 15:29:52.873098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99bed8474d4'
down_revision: Union[str, None] = '66a2f05c1d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('quantity', sa.Integer(), nullable=True), schema='auctora_dev')
    op.add_column('items', sa.Column('weight', sa.Float(), nullable=True), schema='auctora_dev')
    op.add_column('items', sa.Column('height', sa.Float(), nullable=True), schema='auctora_dev')
    op.add_column('items', sa.Column('width', sa.Float(), nullable=True), schema='auctora_dev')
    op.add_column('items', sa.Column('length', sa.Float(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'length', schema='auctora_dev')
    op.drop_column('items', 'width', schema='auctora_dev')
    op.drop_column('items', 'height', schema='auctora_dev')
    op.drop_column('items', 'weight', schema='auctora_dev')
    op.drop_column('items', 'quantity', schema='auctora_dev')
    # ### end Alembic commands ###
