"""updated referral structure in users model

Revision ID: eb313b2e9734
Revises: 44704c3fa208
Create Date: 2025-04-25 16:13:28.088401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb313b2e9734'
down_revision: Union[str, None] = '44704c3fa208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_commisions_paid', sa.Integer(), nullable=True), schema='auctora_dev')
    op.add_column('users', sa.Column('referral_slots_used', sa.Integer(), nullable=True), schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_slots_used', schema='auctora_dev')
    op.drop_column('users', 'referral_commisions_paid', schema='auctora_dev')
    # ### end Alembic commands ###
