"""Added reversed to transaction status enum

Revision ID: fd27cb97b290
Revises: 08cad63dbf7b
Create Date: 2025-05-08 18:43:26.977649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd27cb97b290'
down_revision: Union[str, None] = '08cad63dbf7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE auctora_dev.transaction_status ADD VALUE IF NOT EXISTS 'REVERSED'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
